# Generated by Django 2.0.1 on 2018-01-26 19:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('height_from_sea_level', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('room_number', models.CharField(blank=True, max_length=25)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('display_access_restrictions', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=50)),
                ('manager', models.CharField(blank=True, max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
            ],
        ),
        migrations.CreateModel(
            name='SpotAvailableHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('m', 'monday'), ('t', 'tuesday'), ('w', 'wednesday'), ('th', 'thursday'), ('f', 'friday'), ('sa', 'saturday'), ('su', 'sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scout_server.Spot')),
            ],
            options={
                'verbose_name_plural': 'Spot available hours',
            },
        ),
        migrations.CreateModel(
            name='SpotExtendedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=350)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotextendedinfo', to='scout_server.Spot')),
            ],
            options={
                'verbose_name_plural': 'Spot extended info',
            },
        ),
        migrations.CreateModel(
            name='SpotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='spottypes',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, related_name='spots', to='scout_server.SpotType'),
        ),
        migrations.AlterUniqueTogether(
            name='spotextendedinfo',
            unique_together={('spot', 'key')},
        ),
    ]
